apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitmagnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitmagnet
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bitmagnet
    spec:
      containers:
        - name: bitmagnet
          image: ghcr.io/bitmagnet-io/bitmagnet:latest
          command: ["bitmagnet", "worker", "run", "--keys=http_server", "--keys=queue_server", "--keys=dht_crawler"]
          env:
            - name: CLASSIFIER_DELETE_XXX
              value: "true"
            - name: DHT_CRAWLER_SAVE_FILES_THRESHOLD
              value: "500"
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: bitmagnet-postgres-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_NAME
              valueFrom:
                secretKeyRef:
                  name: bitmagnet-postgres-secret
                  key: POSTGRES_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: bitmagnet-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bitmagnet-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: TMDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bitmagnet-postgres-secret
                  key: TMDB_API_KEY
          ports:
            - containerPort: 3333   # HTTP / Web UI
            - containerPort: 3334   # BitTorrent TCP
            - containerPort: 3334
              protocol: UDP
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "700Mi"
              cpu: "600m"
          livenessProbe:
            httpGet:
              path: /status
              port: 3333
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /status
              port: 3333
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /root/.config/bitmagnet
            - name: classifier-config
              mountPath: /root/.config/bitmagnet/classifier.yml
              subPath: classifier.yml
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: bitmagnet-config-pvc
      - name: classifier-config
        configMap:
          name: bitmagnet-classifier-config