apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bitmagnet-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: bitmagnet.homelab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bitmagnet
                port:
                  number: 3333